/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecondRouteImport } from './routes/second'
import { Route as ClipboardHistoryRouteImport } from './routes/clipboard-history'
import { Route as ClipboardRouteImport } from './routes/clipboard'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondRoute = SecondRouteImport.update({
  id: '/second',
  path: '/second',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipboardHistoryRoute = ClipboardHistoryRouteImport.update({
  id: '/clipboard-history',
  path: '/clipboard-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipboardRoute = ClipboardRouteImport.update({
  id: '/clipboard',
  path: '/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/clipboard-history': typeof ClipboardHistoryRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/clipboard-history': typeof ClipboardHistoryRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/clipboard-history': typeof ClipboardHistoryRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clipboard' | '/clipboard-history' | '/second' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clipboard' | '/clipboard-history' | '/second' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/clipboard'
    | '/clipboard-history'
    | '/second'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipboardRoute: typeof ClipboardRoute
  ClipboardHistoryRoute: typeof ClipboardHistoryRoute
  SecondRoute: typeof SecondRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second': {
      id: '/second'
      path: '/second'
      fullPath: '/second'
      preLoaderRoute: typeof SecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipboard-history': {
      id: '/clipboard-history'
      path: '/clipboard-history'
      fullPath: '/clipboard-history'
      preLoaderRoute: typeof ClipboardHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipboard': {
      id: '/clipboard'
      path: '/clipboard'
      fullPath: '/clipboard'
      preLoaderRoute: typeof ClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipboardRoute: ClipboardRoute,
  ClipboardHistoryRoute: ClipboardHistoryRoute,
  SecondRoute: SecondRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
