// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

import type { ClipboardUpdateEvent } from "./preload";
import type { BatchOverallProgress } from "./ipc/media/schemas";

interface Window {
  electron?: {
    getFilePath: (file: File) => string;
    onNavigate: (callback: (path: string) => void) => () => void;
    onClipboardUpdate: (callback: (event: ClipboardUpdateEvent) => void) => () => void;
    onClipboardWindowOpened: (callback: () => void) => () => void;
  };
  media?: {
    onProgress: (callback: (progress: number) => void) => () => void;
    onBatchProgress: (callback: (progress: BatchOverallProgress) => void) => () => void;
  };
}
